### ISSUE TITLE
Parser error with weight attribute

### ISSUE THREAD

**Issue by rodrigo7491** [ufmg-smite/carcara#12]
Hi,

When solving an instance containing the `:weight` attribute cvc5 outputs `warning: Attribute ':weight' not supported (ignoring this and all following uses)`, but continues normally, and is able to produce an Alethe proof. When encountering this attribute, however, carcara gives the following error:

```
[ERROR] parser error: unknown attribute: ':weight' (on line 17, column 16)
invalid
```

Is there a way to also make carcara ignore this attribute, or is this a current limitation of the tool? Here is a, not so small, example: [ex.zip](https://github.com/ufmg-smite/carcara/files/11555163/ex.zip).

I'm running cvc5 v1.0.5 and carcara v1.0.0, CLI commands below.

`cvc5 --produce-proofs --proof-format=alethe --proof-granularity=theory-rewrite --flatten-ho-chains ex.smt2`
`carcara check --skip-unknown-rules --allow-int-real-subtyping --expand-let-bindings ex.proof ex.smt2`

**Comment by bpandreotti** [comment]
Hi, Rodrigo, thanks for the report!

Carcara used to plainly reject any attributes in annotated terms it didn't know about, which goes against the SMT-LIB specification. f87efb2 fixes this.
