### ISSUE TITLE
Acceptance of Empty Clause Resolution with no Premises

### ISSUE THREAD

**Issue by mbaranr** [ufmg-smite/carcara#19]
smt file:
```
(set-logic QF_UF)
(assert true)
(check-sat)
(exit)
```
proof file:
```
(assume h1 true)
(step t2 (cl) :rule resolution)
```
current output:
```
valid
```
We would expect carcara to not accept this proof as the problem is satisfiable. According to alethe's proof format documentation, the resolution rule should always contain at least 2 clauses. I have carcara's 1.0.0 version installed with cargo:
```
carcara 1.0.0 [git main 589645f]
```

**Comment by bpandreotti** [comment]
Thanks a lot for the bug report! Commit ab8239f fixes this. Now Carcara correctly reports an error:
```
[ERROR] checking failed on step 't2' with rule 'resolution': expected at least 2 premises, got 0
```
