### ISSUE TITLE
Error checking rule div_simplify 

### ISSUE THREAD

**Issue by blishko** [ufmg-smite/carcara#21]
`carcara` currently does not accept the following application of the rule `div_simplify`

```
(step s1 (cl (= (div 5 2) 2)) :rule div_simplify)
```

The error message I am getting is `[ERROR] checking failed on step 's1' with rule 'div_simplify': expected term '2' to be numerical constant 2.5`

According to the error message it seems that `carcara` is interpreting `div` operation from the SMT-LIB theory of integers as a division over reals, instead of the SMT-LIB interpretation of the `div` operator (https://smtlib.cs.uiowa.edu/theories-Ints.shtml).

This problem is present in `carcara 1.1.0` (and current main).

**Comment by bpandreotti** [comment]
Thanks for the bug report! Commit 5b2b818 should fix this.
