### ISSUE TITLE
Handling of unary conjuncts/disjuncts

### ISSUE THREAD

**Issue by rodrigo7491** [ufmg-smite/carcara#27]
In https://github.com/ufmg-smite/carcara/commit/c537c7525f51a1c234216d70697e8ccecbbde256 `and`, `or`, and `xor` were restricted to accurately follow SMT-LIB. Despite not being in the standard, many SMT benchmarks are currently written using unary conjuncts/disjuncts. Would it be possible to relax this input restriction, maybe under a special flag?

**Comment by rodrigo7491** [comment]
See https://github.com/ufmg-smite/carcara/discussions/28. [@blisko ](https://github.com/blishko) is also interested in this :)

**Comment by HanielB** [comment]
I think this is sensible. I think the best is to have a `--strict` flag or something like that that rejects non-SMT-LIB compliant terms, and that is on by default, but that can be disabled by the user. What do you think, @bpandreotti?

**Comment by bpandreotti** [comment]
Sounds good to me. Since we already have a `--strict` flag, I think we can also use it for that.

**Comment by bpandreotti** [comment]
Fixed by 71c1edc1cf990172d139519b5b9f16349b3471b7.
