### ISSUE TITLE
Assume step failed on many SMT-LIB benchmarks

### ISSUE THREAD

**Issue by NotBad4U** [ufmg-smite/carcara#49]
Versions:
-  carcara version: `carcara 1.1.0 [git main 113f5a7]` (current the last commit)
- cvc5 version: `cvc5 1.2.1-dev.144.38fcc340e5 [git 38fcc340e5 on branch main]` 

--- 

Hi everyone,

I am trying to run the SMT-LIB benchmarks to evaluate the Lambdapi reconstruction.
For that, I want to check the file first with Carcara to avoid reconstructing something that I did not even check. 
However, the `carcara check` failed on many samples in [sledgehammer](https://www.starexec.org/starexec/secure/explore/spaces.jsp?id=543087) from UF  and  [QG-classification](https://www.starexec.org/starexec/secure/explore/spaces.jsp?id=541365) from QF_UF. I did not try with other samples, but something similar may happen. The error I am getting is always similar to the one below.

Given this benchmark https://www.starexec.org/starexec/secure/details/benchmark.jsp?id=16637753, if I try to produce a proof with CVC5 and run carcara check, I got this error:
```rust
cargo run -- check --ignore-unknown-rules smtlib_618663.alethe smtlib_618663.smt2
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/carcara check --ignore-unknown-rules smtlib_618663.alethe smtlib_618663.smt2`
[ERROR] checking failed on step 'a1' with rule 'assume': could not match term to any of the original problem premises: (not (=> (not (= f3 f4)) (=> (and (forall ((?v0 S2) (?v1 S2)) (=> (= (f5 (f6 ?v0 ?v1) f7) f1) (forall ((?v2 S2)) (=> (= (f5 (f6 ?v1 ?v2) f7) f1) (= (f5 (f6 ?v0 ?v2) f7) f1))))) (and (forall ((?v0 S2)) (not (= (f5 (f6 ?v0 ?v0) f7) f1))) (forall ((?v0 S2) (?v1 S2)) (=> (not (= ?v0 ?v1)) (or (= (f5 (f6 ?v0 ?v1) f7) f1) (= (f5 (f6 ?v1 ?v0) f7) f1)))))) (and (forall ((?v0 S2) (?v1 S2)) (and (=> (and (= (f5 (f6 ?v0 ?v1) f7) f1) (and (not (= ?v0 f4)) (not (= ?v1 f4)))) (forall ((?v2 S2)) (and (=> (and (= ?v1 f3) (= ?v2 f4)) (or (= ?v0 f3) (= (f5 (f6 ?v0 f3) f7) f1))) (and (=> (and (= (f5 (f6 ?v1 ?v2) f7) f1) (not (= ?v2 f4))) (= (f5 (f6 ?v0 ?v2) f7) f1)) (=> (and (= ?v2 f4) (= (f5 (f6 ?v1 f3) f7) f1)) (or (= ?v0 f3) (= (f5 (f6 ?v0 f3) f7) f1))))))) (and (=> (and (= ?v1 f4) (and (= (f5 (f6 ?v0 f3) f7) f1) (not (= ?v0 f4)))) (forall ((?v2 S2)) (=> (and (= (f5 (f6 f3 ?v2) f7) f1) (not (= ?v2 f4))) (= (f5 (f6 ?v0 ?v2) f7) f1)))) (=> (and (= ?v0 f4) (and (= (f5 (f6 f3 ?v1) f7) f1) (not (= ?v1 f4)))) (forall ((?v2 S2)) (and (=> (= ?v1 f3) (not (= ?v2 f4))) (and (=> (and (= (f5 (f6 ?v1 ?v2) f7) f1) (not (= ?v2 f4))) (= (f5 (f6 f3 ?v2) f7) f1)) (=> (= ?v2 f4) (not (= (f5 (f6 ?v1 f3) f7) f1)))))))))) (forall ((?v0 S2) (?v1 S2)) (=> (not (= ?v0 ?v1)) (or (and (= ?v0 f3) (= ?v1 f4)) (or (and (= (f5 (f6 ?v0 ?v1) f7) f1) (and (not (= ?v0 f4)) (not (= ?v1 f4)))) (or (and (= ?v1 f4) (and (= (f5 (f6 ?v0 f3) f7) f1) (not (= ?v0 f4)))) (or (and (= ?v0 f4) (and (= (f5 (f6 f3 ?v1) f7) f1) (not (= ?v1 f4)))) (or (and (= ?v1 f3) (= ?v0 f4)) (or (and (= (f5 (f6 ?v1 ?v0) f7) f1) (and (not (= ?v1 f4)) (not (= ?v0 f4)))) (or (and (= ?v0 f4) (and (= (f5 (f6 ?v1 f3) f7) f1) (not (= ?v1 f4)))) (and (= ?v1 f4) (and (= (f5 (f6 f3 ?v0) f7) f1) (not (= ?v0 f4)))))))))))))))))
invalid
```

I have the latest version of Carcara, but not the last one for CVC5. However, I do not think it will change anything.
I would like to know if I am running the checker incorrectly. I may need to add some options for this type of proof.

Can someone also confirm that there is a bug and that it is not just my corrupt setup?

**Comment by HanielB** [comment]
The Alethe proofs that cvc5 generates do not trace the elimination of `let` from the input formulas. I assume that is the issue you were seeing. Carcara provides a flag `--expand-let-bindings` to do the check of the proof `assume` and problem `assert` modulo `let`s.
